name: BUILD

on:
  push:
      branches: [danmaku-support]
  pull_request:
      branches: [develop]
  watch:
      types: [started]

jobs:
  build:
    # FIXME: This builds with macOS 10.15. Move this to the 11.0 builders when possible. (See: https://github.com/actions/virtual-environments/issues/2486)
    runs-on:  macos-11.0
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./other/download_libs.sh

      - name: modify scheme
        run: |
          sed -i "" 's/<string>iina<\/string>/<string>iinadv<\/string>/g' iina/Info.plist
          sed -i "" 's/if parsed.scheme != "iina"/if parsed.scheme != "iinadv"/g' iina/AppDelegate.swift

      - name: Build
        run: xcodebuild -project iina.xcodeproj -scheme iina CODE_SIGNING_ALLOWED=NO -configuration Release
        
      - name: 打包app
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/release
          cd ~/Library/Developer/Xcode/DerivedData/iina-*/Build/Products/Release
          mv IINA.app IINA-Danmaku.app
          tar czf IINA-Danmaku.app.tgz IINA-Danmaku.app
          cd -
          find ~/Library/Developer/Xcode/DerivedData/iina-*/Build/Products/Release -name "IINA-Danmaku.app.tgz" | xargs -I {} mv -f {} ./artifact/release/          
      - name: 设置版本号
        run:  echo "ReleaseVersion=`date +%Y%m%d`" >> $GITHUB_ENV
      - name: 校验本地文件
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ env.ReleaseVersion }}
          title: ${{ env.ReleaseVersion }}
          files: |
            ./artifact/release/*
      - name: 上传 IINA-Danmaku.app
        uses: actions/upload-artifact@v2
        with:
          name: IINA-Danmaku.app
          path: ./artifact/release/

#      - name: SSH 连接到 Actions
#        uses: P3TERX/ssh2actions@main
#        env:
#         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
